name: integration

on: push

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run integration test
        run: npm run integration-test
