name: integration-test-workflow

on: pull_request

jobs:
  create-envfile:
    runs-on: ubuntu-latest
    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_JWT_SECRET_KEY: lskjdfhglksjdfhglkjsdg
          file_name: vars.env

  integration-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Integration test
        run: docker compose -f docker-compose.test.yml up --build --exit-code-from testrunner
